// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASJqLJtPftcsHB3e2k1VXSalXKGwVgewg',
    appId: '1:236855486274:web:c0186faf0685ce0a44cadb',
    messagingSenderId: '236855486274',
    projectId: 'chat-app-db7fb',
    authDomain: 'chat-app-db7fb.firebaseapp.com',
    storageBucket: 'chat-app-db7fb.appspot.com',
    measurementId: 'G-B4HGLFZK3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKIuAMuNsMcgyBiNe2Sh3Zk9TOBikWaJk',
    appId: '1:236855486274:android:1d0f792c04bb896c44cadb',
    messagingSenderId: '236855486274',
    projectId: 'chat-app-db7fb',
    storageBucket: 'chat-app-db7fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUS542adxdNifhJU1KlBmbQvPN4vL6PE',
    appId: '1:236855486274:ios:75eede39cc7d4c9644cadb',
    messagingSenderId: '236855486274',
    projectId: 'chat-app-db7fb',
    storageBucket: 'chat-app-db7fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUS542adxdNifhJU1KlBmbQvPN4vL6PE',
    appId: '1:236855486274:ios:75eede39cc7d4c9644cadb',
    messagingSenderId: '236855486274',
    projectId: 'chat-app-db7fb',
    storageBucket: 'chat-app-db7fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASJqLJtPftcsHB3e2k1VXSalXKGwVgewg',
    appId: '1:236855486274:web:368847ea73defcb344cadb',
    messagingSenderId: '236855486274',
    projectId: 'chat-app-db7fb',
    authDomain: 'chat-app-db7fb.firebaseapp.com',
    storageBucket: 'chat-app-db7fb.appspot.com',
    measurementId: 'G-BG11TD0LVQ',
  );
}
